In [1]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [59]:
df = pd.read_csv("hr.csv",sep=';')
df

experience  test_score  interview_score  salary
0        NaN         8.0                9   50000
1        NaN         8.0                6   45000
2       five         6.0                7   60000
3        two        10.0               10   65000
4      seven         9.0                6   70000
5      three         7.0               10   62000
6        ten         NaN                7   72000
7     eleven         7.0                8   80000

# word2num

In [60]:
from word2number import w2n
import math
i = 0
while i<8:
    if type(df.experience[i]) == float:
        if math.isnan(df.experience[i]) == True:
            i +=1
            continue
    df.experience[i]=w2n.word_to_num(df.experience[i])
    i +=1

<ipython-input-60-bf0f86504cb8>:9: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.experience[i]=w2n.word_to_num(df.experience[i])


In [61]:
df

experience  test_score  interview_score  salary
0        NaN         8.0                9   50000
1        NaN         8.0                6   45000
2          5         6.0                7   60000
3          2        10.0               10   65000
4          7         9.0                6   70000
5          3         7.0               10   62000
6         10         NaN                7   72000
7         11         7.0                8   80000

In [64]:
median_experience=math.floor(df.experience.median())
median_test=math.floor(df.test_score.median())

In [67]:
df.experience = df.experience.fillna(median_experience)
df.test_score = df.test_score.fillna(median_test)
df

experience  test_score  interview_score  salary
0           6         8.0                9   50000
1           6         8.0                6   45000
2           5         6.0                7   60000
3           2        10.0               10   65000
4           7         9.0                6   70000
5           3         7.0               10   62000
6          10         8.0                7   72000
7          11         7.0                8   80000

In [68]:
reg = linear_model.LinearRegression()
reg.fit(df[['experience','test_score','interview_score']],df.salary)

LinearRegression()

In [69]:
reg.coef_

array([2813.00813008, 1333.33333333, 2926.82926829])

In [70]:
reg.intercept_

11869.918699186957

In [71]:
reg.predict([[2,9,6]])

array([47056.91056911])

In [72]:
reg.predict([[12,10,10]])

array([88227.64227642])